on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  clang-format:
    strategy:
      matrix:
        directories: [ZEngine, Tetragrama]
    uses: ./.github/workflows/job-clangformat.yml
    with:
      srcDirectory: ${{ matrix.directories }}

  windows:
    needs: clang-format
    uses: ./.github/workflows/windows-build.yml
    with:
      targetFramework: net8.0

  macOS:
    needs: clang-format
    uses: ./.github/workflows/macOS-build.yml
    with:
      targetFramework: net8.0
